### PR TITLE
Logic for importing all layers from a single upload & api endpoint utilizing it.

### PR DESCRIPTION
**Pull request by JivanAmara**

### CODE REVIEW

**Comment by JivanAmara** [comment]
Failures are due to down servers, not code.

**Comment by jj0hns0n** [comment]
Lets switch these calls to a geosolutions geoserver as it seems more reliable.

http://demo.geo-solutions.it/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?1

@JivanAmara I can make this change if you like.

**Comment by JivanAmara** [comment]
Do we want to move to another server or serialize the results of a server so downtime is no longer an issue?

**Comment by jj0hns0n** [comment]
Should be able rebase this with master and it should pass.

**Pull request merged**
