### PR TITLE
Bump angular to 1.4.0

### PR DESCRIPTION
**Pull request by travislbrundage**
Bumping angular and dependencies to 1.4.0. This is to be congruent with a change occurring in Exchange/GeoNode which requires angular 1.4.0.

Nothing appears to break by bumping GeoNode's angular to 1.4.0 and leaving importer's at 1.3.0, but an error message does show up in the console despite the importer still working successfully. This change is made with the intention of being safe and congruent.

Here are the related PR's:
https://github.com/boundlessgeo/exchange/pull/330
https://github.com/boundlessgeo/geonode/pull/68
https://github.com/GeoNode/geonode/pull/3180 [Merged]

### CODE REVIEW

**Comment by emilyashley** [comment]
For reference, 

> error message does show up in the console despite the importer still working successfully 

The error message is `TypeError: $browser.addPollFn is not a function` from angular-cookies.

This occurs because angular-cookies and angular-resource both need to be tied to the same version as the angular.js that's loaded in the browser.

**Comment by travislbrundage** [comment]
Thanks for adding the context here @emilyashley - your analysis is accurate as far as I know. Because core angular is not in the loaded scripts in the _importer_scripts template, it is loaded by packages Exchange/GeoNode decide to include, which leads to the error in this case when they are bumped to `1.4.0` while importer remains on `1.3.0`.

**Comment by travislbrundage** [comment]
Holding off on this for a bit - looking at some issues related to angular bumping.

**Comment by emilyashley** [comment]
Cool beans. I'd love to upgrade MapStory to 1.6.5 as well (we'd been holding back based on importer deps here). 

Taking a look at this tomorrow!

**Pull request closed without merging**
